import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import DropDown from "../components/DropDown";
import Header from "../components/Header";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Renti</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <Header></Header> */}
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#71AAF7] to-[#356dbe]">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-5xl font-lufgaExtraBold tracking-tight text-white sm:text-[5rem]">
              Renting <span className="text-[hsl(280,100%,70%)]">Reimagined</span>
            </h1>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="https://create.t3.gg/en/usage/first-steps"
                target="_blank"
              >
                <h3 className="text-2xl font-lufga">First Steps →</h3>
                <div className="text-lg">
                  Just the basics - Everything you need to know to set up your
                  database and authentication.
                </div>
              </Link>
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="https://create.t3.gg/en/introduction"
                target="_blank"
              >
                <h3 className="text-2xl font-lufgaBold">Documentation →</h3>
                <div className="text-lg">
                  Learn more about Create T3 App, the libraries it uses, and how
                  to deploy it.
                </div>
              </Link>
              <DropDown></DropDown>
            </div>
          </div>
          {/* <div className="container flex flex-col items-center justify-center gap-8 px-4 py-8">
            <h2 className="text-4xl font-lufgaBold text-white">About Us</h2>
            <p className="text-lg text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida arcu et scelerisque scelerisque.</p>
          </div> */}
        </main>
      </Layout>
    </>
  );
};

export default Home;
